### PR TITLE
Support sveld 0.18

### PR DESCRIPTION
**Pull request by mattjennings**
Add support for sveld 0.18 and update the types.

This also changes sveld to be a peer dependency so that it's not locked into a specific sveld version.

### CODE REVIEW

**Comment by mattjennings** [comment]
@niktek @endigo9740 you can try it out by installing `vite-plugin-sveld@next`. Since I've changed sveld to be a peer dependency, you'll also need to npm install sveld now as well.

Let me know if this works well for you, and if so, I'll publish this as 1.1.0.

**Comment by endigo9740** [comment]
@mattjennings Sounds good. It's nearly the day for me so I may opt to allow @niktek test this for us. He's on Australian time so I expect h'll seen this soon. Either way we'll have confirmation back to you within the next 24 hours. Thanks for the quick turn around!

**Comment by endigo9740** [comment]
@mattjennings I had a chance to test quick before I head out for a bit. There's good news and bad news :)

The good news, is the description fields do appear to be working for Slots and Events. The bad news is we're seeing a couple scenarios that appear to be bugs:

Here's how we're defining our JSDoc comments for a component that has three Slots and one forwarded Event:

Screen Shot 2022-10-24 at 5 34 24 PM

## 1. First Slot Always Dropped

You'll note we're adding an empty `@slot` definition, which should come out to a total of 4x slots. But we've noted that regardless of howe we structure or order the comments, the first slot definition is always pruned. The only work around we've discovered is to insert an empty slot to be "sacrificed".

Screen Shot 2022-10-24 at 5 35 00 PM

## 2. Documenting Events Causes Incorrect Data

We've applied a single `on:click` event to our template. This should be forwarded up. Here's what that looks like if we do not specify a JSDocs comment, just allow Sveld to auto-document it:

Screen Shot 2022-10-24 at 5 38 57 PM

The above is correct, though missing the description obviously since one isn't specified. However, when we do try to specify a description, we see two issues:

- The `type` information incorrectly changes from `forwarded` -> `dispatched`
- We lose the `element` value - though I believe this is due to the fact it's being tread as "dispatched"

Screen Shot 2022-10-24 at 5 38 27 PM

Let me know if you would like me to file these as a proper issue on your GitHub Issue tracker. And FYI @niktek is still testing further on his end. But wanted to give you a heads up asap!

**Comment by endigo9740** [comment]
@mattjennings I missed the fact you made Sveld a peer dependency. That should resolve our issue, please feel free to push that release when you can. We'll update accordingly. Thanks again for the quick turn around!

**Comment by mattjennings** [comment]
awesome!

**Pull request merged**
