### PR TITLE
Upgrade to get new features from sveld

### PR DESCRIPTION
**Pull request by niktek**
Hi,

Sveld now allows for custom @tags to be passed through in the description field, so I've just done a version bump of the dependencies to get this new functionality.

Cheers,
Nik

### CODE REVIEW

**Comment by endigo9740** [comment]
Hey @mattjennings, my name is Chris. I'm the project lead and core contributor to Skeleton UI component library:
https://skeleton.dev/

@niktek Had sent this PR a few days ago as we're updating our project to take advantage of Sveld for documentation. In addition to the custom @tags, it seems they've also included support for descriptions on both slots and events, which we really need!

https://github.com/carbon-design-system/sveld/pull/100
https://github.com/carbon-design-system/sveld/pull/99

Would it be possible to coordinate on including these changes as well? It looks like @niktek bumped up to `v0.17.2`, but we would need hit [v0.18.0](https://github.com/carbon-design-system/sveld/releases/tag/v0.18.0) to access these changes.

I'm sure either Nik or I can send another PR to handle this, we just want to make sure the project is still maintained and this will be accepted in a timely manner. Otherwise we may need to opt for fork that we can maintain.

Either way, thanks for your work on the plugin! Great stuff here!

**Comment by mattjennings** [comment]
@endigo9740 @niktek I'll take a look at 0.18 tonight. I imagine it'll be trivial. 

(sorry for the delay, meant to get to this PR over the weekend but other stuff came up)

**Comment by endigo9740** [comment]
@mattjennings Awesome, thank you sir! And completely understand, I just wanted to check in! Let us know if we can help!

**Comment by mattjennings** [comment]
closed in favour of #3

**Pull request closed without merging**
