### PR TITLE
deps: update

### PR DESCRIPTION
**Pull request by jaeh**
update dependencies in package.json

update pnpm-lock.json

### CODE REVIEW

**Comment by retani** [comment]
Merge and release would be greatly appreciated 🙏

**Comment by throni3git** [comment]
yeah, that would be really nice.

my npm says

```
npm error Found: sveld@0.20.2
npm error node_modules/sveld
npm error   dev sveld@"^0.20.2" from the root project
npm error
npm error Could not resolve dependency:
npm error peer sveld@"^0.18.0" from vite-plugin-sveld@1.1.0
npm error node_modules/vite-plugin-sveld
npm error   dev vite-plugin-sveld@"^1.1.0" from the root project
```

i guess this is the reason why i'd like to have an update. does it work with PNPM anyway?

**Comment by throni3git** [comment]
> i guess this is the reason why i'd like to have an update. does it work with PNPM anyway?

no it isn't. this error also occurs when i install from jeahs repo...

**Comment by mattjennings** [comment]
oh man, I totally missed this - super sorry. I've just published 2.0.0 with updated peers for Svelte 4 and sveld 0.20. Let me know if there are any issues.

**Pull request closed without merging**
